/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 5.0 2002/04/20 07:30:13 hardaker Exp $
 */

#include <unistd.h>
#include <signal.h>
#include <sys/syscall.h>

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "nstAgentSubagentObject.h"

/*
 * the variable we want to tie an OID to.  The agent will handle all
 * * GET and SET requests to this variable changing it's value as needed.
 */
static long nstAgentSubagentObject = 0;

int gettid(void)
{
	return (int) syscall(SYS_gettid);
}

#define uSEC 1
#define mSEC (1000 * uSEC)
#define  SEC (1000 * mSEC)
static void handle_get_mode(void)
{
	long int sleeptime;

	if (nstAgentSubagentObject == 10) {
		/* use random time */
		sleeptime = (rand() % 100 + 1) * mSEC;
	} else
		sleeptime = nstAgentSubagentObject * SEC;

	DEBUGMSGTL(("nstAgentSubagentObject", "[%i]: start sleeping=%li\n",
		    gettid(), sleeptime));

	usleep(sleeptime);
	DEBUGMSGTL(("nstAgentSubagentObject", "[%i]: wakeup\n", gettid()));
}

static int test_handler(netsnmp_mib_handler *handler,
			netsnmp_handler_registration *reginfo,
			netsnmp_agent_request_info *reqinfo,
			netsnmp_request_info *requests)
{
	static int x = 0;
	DEBUGMSGTL(("nstAgentSubagentObject", "mode=%i\n", reqinfo->mode));
	if (reqinfo->mode == MODE_GET) {
		if (nstAgentSubagentObject == 20) {
			DEBUGMSGTL(("nstAgentSubagentObject", "returning GENERR\n"));
			return 73;
		} else {
			handle_get_mode();
			#if 0
			x++;
			if ((x % 7) == 0) {
				DEBUGMSGTL(("nstAgentSubagentObject", "returning 72\n"));
				return 72;
			}
			#endif
		}
	}
	DEBUGMSGTL(("nstAgentSubagentObject", "returning 0\n"));
	return SNMP_ERR_NOERROR;
}

void handle_signal(int signal) {
	if (signal == SIGUSR1) {
		long int sleeptime= 1 * SEC;

		DEBUGMSGTL(("nstAgentSubagentObject", "Got signal - SIGUSR1\n"));
		DEBUGMSGTL(("nstAgentSubagentObject", "[%i]: start sleeping=%li\n",
			    gettid(), sleeptime));

		usleep(sleeptime);
		DEBUGMSGTL(("nstAgentSubagentObject", "[%i]: wakeup\n", gettid()));

	} else {
		DEBUGMSGTL(("nstAgentSubagentObject", "Got signal - %d\n", signal));
	}
}

/*
 * our initialization routine, automatically called by the agent
 * (to get called, the function name must match init_FILENAME())
 */

void init_nstAgentSubagentObject(void)
{
	static oid nstAgentSubagentObject_oid[] ={ 1, 3, 6, 1, 4, 1, 8072, 2, 4, 1, 1, 2, 0 };

	if ( signal(SIGUSR1, handle_signal) == SIG_ERR)
		exit(-1);
	else
		DEBUGMSGTL(("nstAgentSubagentObject", "signal handler setup for SIGUSR1\n"));

	DEBUGMSGTL(("nstAgentSubagentObject", "Initializing the nstAgentSubagentObject module\n"));
	DEBUGMSGTL(("nstAgentSubagentObject",
		    "Initalizing nstAgentSubagentObject scalar integer.  Default value = %li\n",
		    nstAgentSubagentObject));

	netsnmp_register_long_instance("nstAgentSubagentObject",
				       nstAgentSubagentObject_oid,
				       OID_LENGTH(nstAgentSubagentObject_oid),
				       &nstAgentSubagentObject, test_handler);

	DEBUGMSGTL(("nstAgentSubagentObject", "Done initalizing nstAgentSubagentObject module\n"));
}
