/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 5.0 2002/04/20 07:30:13 hardaker Exp $
 */

#include <unistd.h>
#include <sys/syscall.h>

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "nstAgentSubagentObject.h"

/*
 * the variable we want to tie an OID to.  The agent will handle all
 * * GET and SET requests to this variable changing it's value as needed.
 */
static long nstAgentSubagentObject = 6;

int gettid(void)
{
        return (int) syscall(SYS_gettid);
}


#define uSEC 1
#define mSEC (1000 * uSEC)
#define  SEC (1000 * mSEC)
static void handle_get_mode(void)
{
        long int sleeptime;

        if (nstAgentSubagentObject == 10) {
                /* use random time */
                sleeptime = (rand() % 1000 + 1) * mSEC;
        } else
                sleeptime = nstAgentSubagentObject * SEC;


        DEBUGMSGTL(("nstAgentSubagentObject", "[%i]: start sleeping=%li\n",
                    gettid(), sleeptime));

        usleep(sleeptime);
        DEBUGMSGTL(("nstAgentSubagentObject", "[%i]: wakeup\n", gettid()));
}

static int test_handler(netsnmp_mib_handler *handler,
                        netsnmp_handler_registration *reginfo,
                        netsnmp_agent_request_info *reqinfo,
                        netsnmp_request_info *requests)
{
        DEBUGMSGTL(("nstAgentSubagentObject", "mode=%i\n", reqinfo->mode));
        if (reqinfo->mode == MODE_GET) {
                if (nstAgentSubagentObject == 20) {
                        DEBUGMSGTL(("nstAgentSubagentObject", "returning GENERR\n"));
                        return SNMP_ERR_GENERR;
                } else
                        handle_get_mode();
        }
        return SNMP_ERR_NOERROR;
}

/*
 * our initialization routine, automatically called by the agent
 * (to get called, the function name must match init_FILENAME())
 */

void init_nstAgentSubagentObject(void)
{
        static oid nstAgentSubagentObject_oid[] ={ 1, 3, 6, 1, 4, 1, 8072, 2, 4, 1, 1, 2, 0 };

        DEBUGMSGTL(("nstAgentSubagentObject", "Initializing the nstAgentSubagentObject module\n"));
        DEBUGMSGTL(("nstAgentSubagentObject",
                    "Initalizing nstAgentSubagentObject scalar integer.  Default value = %li\n",
                    nstAgentSubagentObject));

        netsnmp_register_long_instance("nstAgentSubagentObject",
                                       nstAgentSubagentObject_oid,
                                       OID_LENGTH(nstAgentSubagentObject_oid),
                                       &nstAgentSubagentObject, test_handler);

        DEBUGMSGTL(("nstAgentSubagentObject", "Done initalizing nstAgentSubagentObject module\n"));
}
