#!/bin/bash

[ -z "$IPv4" ] && IPv4=no
[ -z "$IPv6" ] && IPv6=no
[ -z "$DTLSUDP4" ] && DTLSUDP4=yes
[ -z "$DTLSUDP6" ] && DTLSUDP6=no
[ -z "$TCPDUMP" ] && TCPDUMP=no
[ -z "$REMOTE" ] && REMOTE=yes
[ -z "$SNMP_PROTOCOL" ] && SNMP_PROTOCOL=3
2[ -z "$SETX" ] && SETX=""
[ -z "$INFORM" ] && INFORM=no
[ -z "$KILLSNMPD" ] && KILLSNMPD=yes
[ -z "$SETUP_TRAPSESS" ] && SETUP_TRAPSESS=yes
[ -z "$DEBUG" ] && DEBUG=no
# TLS_VALIDATION: peer or trust_anchor
[ -z "$TLS_VALIDATION" ] && TLS_VALIDATION=peer
[ -z "$MD" ] && MD=sha1

[ -z "$IPDEV0" ] && IPDEV0=eth0

[ -z "$REMOTE_IPDEV0" ] && REMOTE_IPDEV0=eth0
[ -z "$REMOTE_IPv4" ] && REMOTE_IPv4=128.224.95.149
[ -z "$REMOTE_IPv6" ] && REMOTE_IPv6=2001:1b70:82a8:90:1284:31:0:149

#####################################################################
TESTDIR=/tmp/snmp/test
CERTDIR=/tmp/snmp/cert

SNMPD_LOG=$TESTDIR/snmpd.log
SNMPD_PID=$TESTDIR/snmpd.pid
SNMPD_CONF_IN=snmpd.conf
SNMPD_CONF=$TESTDIR/snmpd.conf
SNMPD_PORT=161

SNMPTRAPD_LOG=$TESTDIR/snmptrapd.log
SNMPTRAPD_PID=$TESTDIR/snmptrapd.pid
SNMPTRAPD_CONF_IN=snmptrapd.conf
SNMPTRAPD_CONF=$TESTDIR/snmptrapd.conf
SNMPTRAPD_PORT=162
SNMPTRAPD_DTLSUDP_PORT=10162

SNMP_CONF_IN=snmp.conf
SNMP_CONF=$TESTDIR/snmp.conf

SNMP_COMMUNITY=public
SNMPSET_LOG=$TESTDIR/snmpset.log
SNMPWALK_OUT=$TESTDIR/snmpwalk.out
SNMPTRAP_LOG=$TESTDIR/snmptrap.log

DTLSUDP_PORT=10161

LOGTIMESTAMP="logTimestamp 0"

NET_SNMP_CERT=net-snmp-cert

APP_USER=appuser
TSM_USER=tsmuser
EPRIME_CA=ca.eprime.com
EPRIME_EMAIL=admin@eprime.com
HOSTNAME=$(hostname)

TRAP_USER=trapuser
TRAP_PW=trap1234
TRAP_EID=0x80001f8880523983647b8b0356

USM_USER=usmuser
USM_PW=kalle123
USM_EID=0x80001f8880523983647b8b0357
PRIVPROTO=DES

RETRYCOUNT=0
TIMEOUT=3

IPv4_HOST=0.0.0.0
IPv4_LO=127.0.0.1
IPv4_DEV0=$(ip -o -4 addr list $IPDEV0 | head -1 | awk '{print $4}' | cut -d/ -f1)
IPv4_DEV0_LAST=$(echo $IPv4_DEV0 | cut -d'.' -f4)

IPv6_HOST=::
IPv6_LO=::1

TCPDUMP_TIMEOUT=70
if [ "$KILLSNMPD" == "yes" ]; then
    TCPDUMP_TIMEOUT=5
fi

NOTE='echo -e \n--- '
HEAD="head -3"
BASH="bash $SETX -c"
SSH_REMOTE="ssh $REMOTE_IPv4"

#####################################################################
function snmp_kill () {
    $NOTE "Kill all running snmp servers"

    killall snmpd
    sleep 2
    killall snmptrapd
    sleep 1

    rm -f $SNMPTRAPD_LOG* $SNMPTRAPD_PID
    rm -f $SNMPD_LOG $SNMPD_PID
}

function prepare () {
    if [ ! -e $TESTDIR ]; then
	mkdir -p $TESTDIR
    fi

    prepare_config
    prepare_remote
}

PREPARE_REMOTE=$TESTDIR/prepare_remote
function prepare_remote () {
    if [ "$DEBUG" == "yes" ]; then
	local snmptrapd_debug="-Dtrap,usm,tsm,dtlsudp,tsm,9:dtlsudp,9:dtlsudp:* -d"
    fi

    if [ "$REMOTE" == "yes" ]; then
	if [ ! -e $PREPARE_REMOTE ]; then
	    $NOTE "preparing remote IP"
	    $SSH_REMOTE "killall snmptrapd"
	    $SSH_REMOTE "ifconfig $REMOTE_IPDEV0 inet6 add $REMOTE_IPv6/64"
	    $SSH_REMOTE "ip -6 route add default dev $REMOTE_IPDEV0"
	    $SSH_REMOTE "rm -rf $TESTDIR $CERTDIR"
	    $SSH_REMOTE "mkdir -p $TESTDIR $CERTDIR $SNMP_PERSISTENT_DIR"
	    rsync -az $TESTDIR/ $REMOTE_IPv4:$TESTDIR
	    rsync -az $CERTDIR/ $REMOTE_IPv4:$CERTDIR
	    $SSH_REMOTE "sed -i 's/^clientaddr/#clientaddr/' $SNMP_CONF"
	    touch $PREPARE_REMOTE
	fi
	local snmptrapd_servers=()
	snmptrapd_servers+=("udp:$SNMPTRAPD_PORT")
	snmptrapd_servers+=("udp6:$SNMPTRAPD_PORT")
	snmptrapd_servers+=("dtlsudp:$IPv4_HOST:$SNMPTRAPD_DTLSUDP_PORT")
	snmptrapd_servers+=("dtlsudp6:[$IPv6_HOST]:$SNMPTRAPD_DTLSUDP_PORT")

	$NOTE "starting remote snmptrapd"
	$SSH_REMOTE "killall snmptrapd"
	$SSH_REMOTE "rm -f SNMPTRAPD_LOG SNMPTRAPD_PID"
	echo "REMOTE: snmptrapd $snmptrapd_debug -C -c $SNMPTRAPD_CONF -Lf $SNMPTRAPD_LOG -p $SNMPTRAPD_PID ${snmptrapd_servers[@]}"
	$SSH_REMOTE "source $SNMPENV; snmptrapd $snmptrapd_debug -C -c $SNMPTRAPD_CONF -Lf $SNMPTRAPD_LOG -p $SNMPTRAPD_PID ${snmptrapd_servers[@]}"
    fi
}

PREPARE_IP=$TESTDIR/prepare_ip
function prepare_ip () {
    $NOTE $FUNCNAME
    IPv6_DEV0=$(ip -o -6 addr list $IPDEV0 | grep global | head -1 | awk '{print $4}' | cut -d/ -f1)
    if [ -z $IPv6_DEV0 ]; then
	# set global IPv6
	IPv6_DEV0=2001:1b70:82a8:90:1284:31:0:${IPv4_DEV0_LAST}
	ifconfig $IPDEV0 inet6 add $IPv6_DEV0/80
    fi
}

function prepare_config ()
{
    $NOTE $FUNCNAME

    create_cert
    get_cert
    create_snmp_conf $SNMP_CONF_IN $SNMP_CONF
    create_snmpd_conf $SNMPD_CONF_IN $SNMPD_CONF
    create_snmptrapd_conf $SNMPTRAPD_CONF_IN $SNMPTRAPD_CONF
    export_env
}

function create_cert ()
{
    local ca_config="--org EPRIME --unit RCS --country SE --province DALARNA --locality FALUN --email $EPRIME_EMAIL --host $HOSTNAME"
    local cert_config="--org EPRIME --unit RCS --country SE --province DALARNA --locality FALUN --email $EPRIME_EMAIL \
		       --san DNS:$HOSTNAME --with-ca $EPRIME_CA"

    $NOTE $FUNCNAME
    if [ ! -d $CERTDIR ]; then
	$BASH "echo Using MD=$MD"
	$BASH "$NET_SNMP_CERT genca -I -n $EPRIME_CA $ca_config -C $CERTDIR"

	$BASH "$NET_SNMP_CERT gencert -I -t snmpd --cn $TSM_USER $cert_config --san email:${EPRIME_EMAIL} -C $CERTDIR"
	$BASH "$NET_SNMP_CERT gencert -I -t snmpapp --cn $APP_USER $cert_config -C $CERTDIR"
	$BASH "$NET_SNMP_CERT gencert -I -t snmptrapd --cn $TRAP_USER $cert_config -C $CERTDIR"
    fi
}

function get_cert ()
{
    $NOTE $FUNCNAME
    caCert=$(openssl x509 -noout -in $CERTDIR/tls/ca-certs/$EPRIME_CA.crt -fingerprint -$MD | cut -d= -f2)
    snmpdCert=$(openssl x509 -noout -in $CERTDIR/tls/certs/snmpd.crt -fingerprint -$MD | cut -d= -f2)
    appCert=$(openssl x509 -noout -in $CERTDIR/tls/certs/snmpapp.crt -fingerprint -$MD | cut -d= -f2)
    trapdCert=$(openssl x509 -noout -in $CERTDIR/tls/certs/snmptrapd.crt -fingerprint -$MD | cut -d= -f2)

    show_cert
}

function show_cert ()
{
    $NOTE $FUNCNAME

    echo CA_CERT: $caCert
    echo SNMPD_CERT: $snmpdCert
    echo APP_CERT: $appCert
    echo TRAPD_CERT: $trapdCert
}

function create_snmpd_conf ()
{
    local conf_in=$1
    local conf=$2
    if [ $INFORM == "yes" ]; then
	inform="-Ci"
    fi
    if [ "$SETUP_TRAPSESS" == "yes" ]; then
	local TRAPSESS="trapsess $inform -v 3 -r $RETRYCOUNT -t $TIMEOUT"
    else
	local TRAPSESS="## trapsess $inform -v 3 -r $RETRYCOUNT -t $TIMEOUT"
    fi
    local TRAPSESS_USM="$TRAPSESS -e $TRAP_EID -a MD5 -A $TRAP_PW -x $PRIVPROTO -X $TRAP_PW -l authNoPriv -u $TRAP_USER"
    local TRAPSESS_TSM=$TRAPSESS

    $NOTE $FUNCNAME

    cp $conf_in $conf

#    echo "engineID $TRAP_EID" >> $conf
#    echo "oldEngineID $TRAP_EID" >> $conf
    echo "exactEngineID $TRAP_EID" >> $conf
    echo "createUser $USM_USER MD5 \"$USM_PW\" $PRIVPROTO \"$USM_PW\"" >> $conf
    echo "createUser $TRAP_USER MD5 \"$TRAP_PW\" $PRIVPROTO \"$TRAP_PW\"" >> $conf
    echo "rwuser $USM_USER" >> $conf
    echo "certSecName 10 $appCert --cn" >> $conf
    echo "rwuser -s tsm $APP_USER authpriv" >> $conf
    echo "trapcommunity public" >> $conf
    echo "[snmp] $LOGTIMESTAMP" >> $conf

    if [ "$IPv4" == "yes" ]; then
	if [ $SNMP_PROTOCOL == "3" ]; then
	    echo "$TRAPSESS_USM udp:$IPv4_DEV0:$SNMPTRAPD_PORT" >> $conf
	elif [ $SNMP_PROTOCOL == "2c" ]; then
	    echo "trap2sink udp:$IPv4_DEV0:$SNMPTRAPD_PORT" >> $conf
	fi
    fi

    if [ "$IPv6" == "yes" ]; then
	if [ $SNMP_PROTOCOL == "3" ]; then
	    echo "$TRAPSESS_USM udp6:$IPv6_DEV0:$SNMPTRAPD_PORT" >> $conf
	elif [ $SNMP_PROTOCOL == "2c" ]; then
	    echo "trap2sink udp6:[$IPv6_DEV0]:$SNMPTRAPD_PORT" >> $conf
	fi
    fi

    if [ "$DTLSUDP4" == "yes" ] || [ "$DTLSUDP6" == "yes" ]; then
	if [ "$TLS_VALIDATION" == "peer" ]; then
	    local tls_options="-T peerCert=$trapdCert"
	    #echo "[snmp] peerCert $trapdCert" >> $conf
	else
	    local tls_options="-T trust_cert=$caCert -T their_hostname=$HOSTNAME"
	    echo "[snmp] trustCert $caCert" >> $conf
	fi
	echo "[snmp] localCert $snmpdCert" >> $conf

#	echo "certSecName 11 $trapdcert --cn" >> $conf
#	echo "snmpTlstmCertToTSNEntry 100 $trapdCert --any  1"  >> $conf
	echo "rwuser -s tsm $TSM_USER authpriv" >> $conf

	if [ "$DTLSUDP4" == "yes" ]; then
	    echo "$TRAPSESS_TSM $tls_options dtlsudp:$IPv4_DEV0:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
	fi
	if [ "$DTLSUDP6" == "yes" ]; then
	    echo "$TRAPSESS_TSM dtlsudp6:[$IPv6_DEV0]:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
	fi
    fi
}

function create_snmptrapd_conf ()
{
    local conf_in=$1
    local conf=$2

    $NOTE $FUNCNAME

    cp $conf_in $conf
    echo "exactEngineID $TRAP_EID" >> $conf
    echo createUser -e $TRAP_EID $TRAP_USER MD5 \"$TRAP_PW\" $PRIVPROTO \"$TRAP_PW\" >> $conf
    echo "authUser log $TRAP_USER" >> $conf

    if [ "$DTLSUDP4" == "yes" ] || [ "$DTLSUDP6" == "yes" ]; then
	echo "certSecName 10 $snmpdCert --cn" >> $conf
	echo "certSecName 11 $appCert --cn" >> $conf
	echo "[snmp] trustCert $caCert" >> $conf
	#echo "[snmp] localCert $trapdCert" >> $conf
	echo "authuser log -s tsm $TSM_USER authpriv" >> $conf
	echo "authuser log -s tsm $APP_USER authpriv" >> $conf
    fi
    echo [snmp] $LOGTIMESTAMP >> $conf
}

function create_snmp_conf ()
{
    local conf_in=$1
    local conf=$2

    $NOTE $FUNCNAME

    cp $conf_in $conf
    echo "defCommunity $SNMP_COMMUNITY" >> $conf
    if [ "$DTLSUDP4" == "yes" ] || [ "$DTLSUDP6" == "yes" ]; then
	#echo "trustCert $caCert" >> $conf
	echo "localCert $appCert" >> $conf
	#echo "peerCert  $snmpdCert" >> $conf
    fi
    echo $LOGTIMESTAMP >> $conf
}

SNMPENV=$TESTDIR/snmpenv
function export_env ()
{
    $NOTE $FUNCNAME

    echo "export SNMP_PERSISTENT_DIR=$TESTDIR/persist" > $SNMPENV
    echo "export SNMPCONFPATH=$TESTDIR:$CERTDIR:$SNMP_PERSISTENT_DIR" >> $SNMPENV
    echo "export MD=$MD" >> $SNMPENV
    source $SNMPENV
    mkdir -p $SNMP_PERSISTENT_DIR
}

function set_servers()
{
    SNMPD_SERVERS=()
    SNMPTRAPD_SERVERS=()
    SNMPD_SERVERS+=("udp:$IPv4_HOST:$SNMPD_PORT")
    SNMPTRAPD_SERVERS+=("udp:$SNMPTRAPD_PORT")
    SNMPD_SERVERS+=("udp6:[$IPv6_HOST]:$SNMPD_PORT")
    SNMPTRAPD_SERVERS+=("udp6:$SNMPTRAPD_PORT")
    SNMPD_SERVERS+=("dtlsudp:$IPv4_HOST:$DTLSUDP_PORT")
    SNMPTRAPD_SERVERS+=("dtlsudp:$IPv4_HOST:$SNMPTRAPD_DTLSUDP_PORT")
    SNMPD_SERVERS+=("dtlsudp6:[$IPv6_HOST]:$DTLSUDP_PORT")
    SNMPTRAPD_SERVERS+=("dtlsudp6:[$IPv6_HOST]:$SNMPTRAPD_DTLSUDP_PORT")
}

function snmp_start () {
    if [ "$DEBUG" == "yes" ]; then
	local snmptrapd_debug="-DAW,trap,usm,tsm,dtlsudp,tsm,9:dtlsudp,9:dtlsudp:*,sess_process_packet,snmptrapd,9:openssl:fingerprint,cert:find:params,tls,tlsbase,tls:*,tls_x509:* -d"
	#local snmptrapd_debug="-DALL -d"

	#local snmpd_debug="-d -Dtrap,trap:*,usm,tsm,tls,openssl,cert,dtlsudp,9:dtlsudp,9:dtlsudp:*,9:openssl,9:openssl:fingerprint,9:tlstmParams,9dtlsudp,snmptls,snmp_openssl,snmpNotifyTable,snmpTargetAddrEntry,snmpTargetParamsEntry,udpbase,netsnmp,send_notifications,snmp_build,snmpv3_build,netsnmp_udp6,AW,snmp_sess_add,target_sessions,netsnmp_udpbase,snmpv3,netsnmp_sockaddr_in,netsnmp_sockaddr_in6_2,snmp_api,9:cert,sslctx_client,tls_x509:verif,tlstmCertToTSNTable:save,read_config,cert:find:params,cert:index:dir,9:cert:file:add,9:cert:read,read_config:store,tlstmCertToTSNTable:save,tlstmCertToTSNTable,ssl:cert:chain"
	local snmpd_debug="-DALL -d"
    fi
    $NOTE $FUNCNAME
    echo '/tmp/core.%e.%p' > /proc/sys/kernel/core_pattern
    ulimit -c unlimited

    echo "snmptrapd -C -c $SNMPTRAPD_CONF -Lf $SNMPTRAPD_LOG -p $SNMPTRAPD_PID $snmptrapd_debug ${SNMPTRAPD_SERVERS[@]}"
    snmptrapd -C -c $SNMPTRAPD_CONF -Lf $SNMPTRAPD_LOG -p $SNMPTRAPD_PID $snmptrapd_debug ${SNMPTRAPD_SERVERS[@]}
    echo "snmpd -V -a -C -c $SNMPD_CONF -Lf $SNMPD_LOG -p $SNMPD_PID $snmpd_debug ${SNMPD_SERVERS[@]}"
    snmpd -C -c $SNMPD_CONF -Lf $SNMPD_LOG -p $SNMPD_PID $snmpd_debug ${SNMPD_SERVERS[@]}
    sleep 3
}

TCPDUMP_CAP=$TESTDIR/tcpdump.pcap
function tcpdump_capture ()
{
    local interface=$1
    local rotate_seconds=$2
    local filecount=1
    if [ "$TCPDUMP" == "yes" ]; then
	tcpdump -G $rotate_seconds -W $filecount -w $TCPDUMP_CAP -i $interface &
	sleep 1
    fi
}

function tcpdump_read ()
{
    if [ "$TCPDUMP" == "yes" ]; then
	# workaround: need a last package to close the tcpdump capture
	ping6 -c 1 ::1 >/dev/null
	tcpdump -T snmp -r $TCPDUMP_CAP \
		port $SNMPD_PORT or \
		port $DTLSUDP_PORT or \
		port $SNMPTRAPD_PORT or \
		port $SNMPTRAPD_DTLSUDP_PORT
    fi
}

function get_ipv ()
{
    echo $1 | grep : >/dev/null
    if [ $? = 0 ]; then
	# IPv6
	printf "6"
    else
	# IPv4
	printf "4"
    fi
}

function get_proto ()
{
    if [ $1 = $SNMPTRAPD_PORT ]; then
	printf "udp"
    else
	printf "dtlsudp"
    fi
}

function convert_ip2hex ()
{
    local host=$1
    local port=$2

    printf "0x"
    if [ $(get_ipv $host) = 6 ]; then
	echo $host | grep :: >/dev/null
	if [ $? = 0 ]; then
	    no_of_colons=$(echo $host | tr -d -c ':' | awk '{ print length; }')
	    case $no_of_colons in
		7)
		    host=$(echo $host | sed 's/::/:0:/')
		    ;;
		6)
		    host=$(echo $host | sed 's/::/:0:0:/')
		    ;;
		5)
		    host=$(echo $host | sed 's/::/:0:0:0:/')
		    ;;
		4)
		    host=$(echo $host | sed 's/::/:0:0:0:0:/')
		    ;;
	    esac
	fi
	for i in $(echo $host | tr ':' ' '); do
	    printf "%04x" $(echo $((16#$i)))
	done
    else
	for i in $(echo $host | tr '.' ' '); do
	    printf "%02x" $i
	done
    fi
    printf "%04x" $port
    printf "\n"
}

function configure_mib_dtlsudp()
{
    local host=$1
    local targetaddr=$(convert_ip2hex $2 $3)
    local ipv=$(get_ipv $2)
    local proto=$(get_proto $3)${ipv}
    local obj="'mytrap_${proto}'"
    local link=mytrap_${proto}
    #local link=internal0
    #local snmpset_debug="-Dsnmp -d"

    echo -e "\n--- HOST: $host TRAPADDR: $2:$3 ($targetaddr) OBJ=$obj"

    #snmpusm -v 3 -u $USM_USER  -n "" -l authNoPriv -a MD5 -A $USM_PW $host create $TRAP_USER $USM_USER
    #snmpusm -v 3 -x $PRIVPROTO -u $TRAP_USER -n "" -l authNoPriv -a MD5 -A $USM_PW $host passwd $USM_PW $TRAP_PW
    #snmpget -v 3 -u $TRAP_USER -n "" -l authNoPriv -a MD5 -A $TRAP_PW $host sysUpTime.0

    echo $host | grep dtlsudp >/dev/null
    if [ "$?" -eq 0 ]; then
	# TSM
	local SNMPSET="snmpset -v 3 -T peerCert=$snmpdCert $host"
    else
	# USM
	local SNMPSET="snmpset $snmpset_debug -v 3 -r 0 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host"
    fi

    # snmpTargetParams
    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsRowStatus.$obj = 5
    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsStorageType.$obj = 3
    if [ $proto = dtlsudp4 ] || [ $proto = dtlsudp6 ]; then
	$SNMPSET SNMP-TARGET-MIB::snmpTargetParamsMPModel.$obj = 3
	$SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityModel.$obj = 4
	$SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityName.$obj = dns:$HOSTNAME
	$SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityLevel.$obj = 3
    else
	if [ $SNMP_PROTOCOL == "3" ]; then
	    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsMPModel.$obj = 3
	    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityModel.$obj = 3
	    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityName.$obj = $TRAP_USER
	    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityLevel.$obj = 3
	else
	    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsMPModel.$obj = 1
	    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityModel.$obj = 2
	    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityName.$obj = public
	    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityLevel.$obj = 1
	fi
    fi

    # snmpNotify
    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyRowStatus.$obj = 5
    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyTag.$obj = $link
    if [ $INFORM == "yes" ]; then
	notifytype=2
    else
	# trap
	notifytype=1
    fi
    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyType.$obj = $notifytype
    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyStorageType.$obj = 3

    # snmpTargetAddr
    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrRowStatus.$obj = 5
    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTimeout.$obj = ${TIMEOUT}00
    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrRetryCount.$obj = $RETRYCOUNT
    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTagList.$obj = $link
    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrParams.$obj = $link
    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrStorageType.$obj = 3
    if [ $proto = dtlsudp4 ] || [ $proto = dtlsudp6 ]; then
       $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTDomain.$obj = SNMP-TLS-TM-MIB::snmpDTLSUDPDomain
    fi
    if [ $proto = udp6 ]; then
	$SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTDomain.$obj = SNMPv2-SMI::mib-2.100.1.2
    fi
    if [ $proto = udp4 ]; then
	$SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTDomain.$obj = SNMPv2-TM::snmpUDPDomain
    fi
    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTAddress.$obj x $targetaddr

    # tlstmAddrTable TBD

    # enable the trap?
    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrRowStatus.$obj = 1
    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsRowStatus.$obj = 1
    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyRowStatus.$obj = 1
}

function get_mib()
{
    local host=$1
    local oids="SNMP-TARGET-MIB SNMP-NOTIFICATION-MIB SNMP-TLS-TM-MIB"
    local oid=""

    $NOTE $FUNCNAME $host

    echo $host | grep dtlsudp >/dev/null
    if [ "$?" -eq 0 ]; then
	SNMPWALK="snmpbulkwalk -v 3 -r 2 -t 10 -T peerCert=$snmpdCert $host"
    else
	SNMPWALK="snmpbulkwalk -v 3 -r 2 -t 10 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host"
    fi

    local status=1
    while [ $status != 0 ]; do
	$BASH "$SNMPWALK . > $SNMPWALK_OUT"
	status=$?
	echo status: $status
	sleep 1
    done

    for oid in $oids; do
	$NOTE "GET $oid"
	grep "^${oid}" $SNMPWALK_OUT
    done
}

function send_trap () {
    local host=$1
    local trap_oid="NET-SNMP-EXAMPLES-MIB::netSnmpExampleHeartbeatNotification"
    local oid=netSnmpExampleHeartbeatRate
    if [ $DEBUG == "yes" ]; then
	#local trap_debug="-Lf $SNMPTRAP_LOG -Dtrap,usm,tsm -d"
	#local trap_debug="-Lo -Dtrap,usm,tsm -d"
	local trap_debug="-Lf $SNMPTRAP_LOG -DALL -d"
    fi
    if [ $INFORM == "yes" ]; then
	local inform="-Ci"
    fi
    local SNMPTRAP="snmptrap $inform $trap_debug -v 3 -r 0 -t 2"

    $NOTE "Send TRAP $host v$SNMP_PROTOCOL"
    if [ $SNMP_PROTOCOL == "1" ]; then
	$BASH "snmptrap $trap_debug -v $SNMP_PROTOCOL $host $trap_oid \"\"  6 17 \"\"  $oid i $1"
    elif [ $SNMP_PROTOCOL == "2c" ]; then
	$BASH "snmptrap $trap_debug -v $SNMP_PROTOCOL $host \"\" $trap_oid $oid i $2"
    elif [ $SNMP_PROTOCOL == "3" ]; then
	echo $host | grep dtlsudp >/dev/null
	if [ "$?" -eq 0 ]; then
	    # TSM
	    if [ "$TLS_VALIDATION" == "peer" ]; then
		$BASH "$SNMPTRAP -T peerCert=$trapdCert -l authPriv $host \"\" $trap_oid $oid i $2"
	    else
		#$BASH "$SNMPTRAP -T trust_cert=$caCert -l authPriv $host \"\" $trap_oid $oid i $2"
		$BASH "$SNMPTRAP -T trust_cert=$caCert -T their_hostname=$HOSTNAME -l authPriv $host \"\" $trap_oid $oid i $2"
	    fi
	else
	    # USM
	    $BASH "$SNMPTRAP -e $TRAP_EID -a MD5 -A $TRAP_PW -x $PRIVPROTO -X $TRAP_PW -l authNoPriv -u $TRAP_USER $host \"\" $trap_oid $oid i $2"
	fi
    fi
}

function send_traps () {
    if [ "$IPv4" == "yes" ]; then
	send_trap $CONFIG_IPv4:$SNMPTRAPD_PORT 4
    fi
    if [ "$IPv6" == "yes" ]; then
	send_trap udp6:[$CONFIG_IPv6]:$SNMPTRAPD_PORT 6
    fi
    if [ "$DTLSUDP4" == "yes" ]; then
	send_trap dtlsudp:$CONFIG_IPv4:$SNMPTRAPD_DTLSUDP_PORT 44
	#send_trap dtlsudp:$HOSTNAME:$SNMPTRAPD_DTLSUDP_PORT 44
    fi
    if [ "$DTLSUDP6" == "yes" ]; then
	send_trap dtlsudp6:[$CONFIG_IPv6]:$SNMPTRAPD_DTLSUDP_PORT 66
    fi
}

function configure_mib ()
{
    if [ "$IPv4" == "yes" ]; then
	configure_mib_dtlsudp $CONFIG_HOST $CONFIG_IPv4 $SNMPTRAPD_PORT
    fi
    if [ "$IPv6" == "yes" ]; then
	configure_mib_dtlsudp $CONFIG_HOST $CONFIG_IPv6 $SNMPTRAPD_PORT
    fi
    if [ "$DTLSUDP4" == "yes" ]; then
	configure_mib_dtlsudp $CONFIG_HOST $CONFIG_IPv4 $SNMPTRAPD_DTLSUDP_PORT
    fi
    if [ "$DTLSUDP6" == "yes" ]; then
	configure_mib_dtlsudp $CONFIG_HOST $CONFIG_IPv6 $SNMPTRAPD_DTLSUDP_PORT
    fi
    get_mib $CONFIG_HOST
}

function usage()
{
    echo -e "\n$(basename $0) -h -c -C trap_traget\n"
    echo -e " trap_target = <loopback|local|remote>"
    echo -e " -c   clean: stop snmp servers and remove tmp directory before running the test"
    echo -e " -C   cleanall: including generated certificates"
    echo -e ""
    echo -e "use ENV variables to configure test"
    echo -n " IPv4=$IPv4"
    echo -n " IPv6=$IPv6"
    echo -n " DTLSUDP4=$DTLSUDP4"
    echo -n " DTLSUDP6=$DTLSUDP6"
    echo -n " TCPDUMP=$TCPDUMP"
    echo -n " REMOTE=$REMOTE"
#    echo -n " SNMP_PROTOCOL=$SNMP_PROTOCOL"
    echo -n " INFORM=$INFORM"
    echo -n " KILLSNMPD=$KILLSNMPD"
    echo -n " SETUP_TRAPSESS=$SETUP_TRAPSESS"
    echo -n " DEBUG=$DEBUG"
    echo -n " TLS_VALIDATION=$TLS_VALIDATION"
    echo -n " MD=$MD"
    echo -e " $0"
}

###########################################
# main

while getopts "cCh" opt; do
    case $opt in
	c)
	    snmp_kill
	    rm -rf $TESTDIR
	    ;;
	C)
	    snmp_kill
	    rm -rf $TESTDIR $CERTDIR
	    ;;
	h)
	    usage
	    exit 0
	    ;;
	*)
	    usage
	    exit 0
	    ;;

    esac
done
shift $((OPTIND-1))
if [ "$1" = "" ]; then
    trap_target=loopback
else
    trap_target=$1
fi

CONFIG_HOST=$IPv4_HOST:$SNMPD_PORT
#CONFIG_HOST=udp6:[$IPv6_HOST]:$SNMPD_PORT
#CONFIG_HOST=dtlsudp:$IPv4_LO:$DTLSUDP_PORT
#CONFIG_HOST=dtlsudp6:[$IPv6_LO]:$DTLSUDP_PORT

prepare_ip

if [ $trap_target = local ]; then
    CONFIG_IPv4=$IPv4_DEV0
    CONFIG_IPv6=$IPv6_DEV0
elif [ $trap_target = loopback ]; then
    CONFIG_IPv4=$IPv4_LO
    CONFIG_IPv6=0:0:0:0:0:0:0:1
else
    REMOTE=yes
    CONFIG_IPv4=$REMOTE_IPv4
    CONFIG_IPv6=$REMOTE_IPv6
fi

$NOTE $(date) IPv4: $CONFIG_IPv4 IPv6: $CONFIG_IPv6

snmp_kill
prepare

set_servers
snmp_start

configure_mib

send_traps

if [ "$TCPDUMP" == "yes" ]; then
    $NOTE capture tcpdump for traps
    tcpdump_capture any $TCPDUMP_TIMEOUT
fi

if [ "$KILLSNMPD" == "yes" ]; then
    killall snmpd
fi

sleep $TCPDUMP_TIMEOUT

if [ "$TCPDUMP" == "yes" ]; then
    tcpdump_read
    cp $TCPDUMP_CAP .
fi

echo -e "\n---- LOCAL snmptrapd.log"
cat $SNMPTRAPD_LOG
if [ $trap_target = remote ]; then
    echo -e "\n---- REMOTE snmptrapd.log"
    scp $REMOTE_IPv4:$SNMPTRAPD_LOG /dev/stdout
fi

exit $status

# TODO
- USM traps not working (inform works)
- Define NETSNMP_FEATURE_REMOVE_TLSTMADDR_GET_SERVERID
