/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 5.0 2002/04/20 07:30:13 hardaker Exp $
 */
#ifndef NSTAGENTSUBAGENTOBJECT_H
#define NSTAGENTSUBAGENTOBJECT_H

#define MAXSTRLEN 32

#define MAGIC_ENTRY 0
#define MAGIC_DEV 1
#define MAGIC_LEVEL 2
#define MAGIC_NUMDEV 3
#define MAGIC_STATUS 4

struct TestTableEntry {
  char dev[MAXSTRLEN];
  char level[MAXSTRLEN];
  int numdev;
  int status;
}; 

/*
 * function declarations 
 */
void            init_nstAgentSubagentObject(void);

#endif                          /* NSTAGENTSUBAGENTOBJECT_H */
