#!/bin/bash
#set -x

TESTDIR=$PWD/tmp
SNMPD_LOG=$TESTDIR/snmpd.log
SNMPD_AGENT_LOG=$TESTDIR/agentx.log

snmp_kill()
{
    killall -w subagent &>/dev/null
    killall -w snmpd  &>/dev/null
}

snmp_start()
{
    local snmpd_dbg="-Dagentx/master,snmp_agent"
    
    snmpd -Lf $SNMPD_LOG $snmpd_dbg  -C --rwcommunity=public --master=agentx udp:161
    ./subagent &
    sleep 1
}

prepare() {
    echo '/tmp/core.%e.%p' > /proc/sys/kernel/core_pattern
    ulimit -c unlimited
    mkdir -p $TESTDIR
    make clean
    make
}

snmp_kill
prepare
snmp_start
