#!/bin/bash
cd /root/net-snmp
git remote -v
git branch
autoreconf
./configure --prefix=/usr \
		--with-persistent-directory=/var/lib/net-snmp \
		--with-mib-modules='smux tlstm-mib tsm-mib examples/example examples/notification' \
		--with-security-modules="tsm" \
		--with-transports="TLSTCP DTLSUDP" \
		--enable-shared \
		--with-defaults \
		--enable-ipv6 \
		--with-cflags="-g -O2" \
		--without-elf
make -j
make -j docs
make -j install
