FROM ubuntu:19.04
MAINTAINER Anders Wallin

WORKDIR /root

ENV TERM xterm
ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive

# Preparing packages needed by snmp 
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y apt-utils
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y git libpopt-dev uuid-dev libxml2-dev automake autoconf libtool flex \
	bison make libc6 libc6-dev libglib2.0-0 libglib2.0-dev libpopt-dev python-pip python-dev emacs tzdata tmux man libperl-dev

# Installing snmp repos
RUN (git clone git://git.code.sf.net/p/net-snmp/code net-snmp)
RUN (cd net-snmp; git remote add wayline git://git.code.sf.net/u/wayline/net-snmp; git fetch --all)

RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y libssl-dev net-tools psmisc gdb strace tcpdump iputils-ping \
    ssh sshpass tig doxygen iproute2 rsync smitools tree moreutils man-db

# for ci/build.sh
RUN DEBIAN_FRONTEND=noninteractive; apt-get install -y libsensors4-dev libmysqlclient-dev libatm1-dev

RUN (sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config)

RUN (echo root:root | chpasswd)
RUN (mkdir /root/.ssh)
RUN (echo "StrictHostKeyChecking no" > /root/.ssh/config)
RUN (echo "UserKnownHostsFile=/dev/null" >> /root/.ssh/config)
RUN (echo "LogLevel quiet" >> /root/.ssh/config)

ADD snmp/.gitconfig /root/.gitconfig
ADD snmp/.tmux.conf /root/.tmux.conf
ADD snmp/build /root/build

ENTRYPOINT ["/bin/bash"]
