#!/bin/bash

DIR=$(dirname $(realpath $0))

USM_PW="kalle123"
USM_USER="usmuser"
host="udp6:[::]:161"
SNMPSET="snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host"
    
function STATUS {
    local status=$1
    if [ $status -ne 0 ]; then
        echo "ERROR: $status"
    fi
    return $status
}

function cache_disable ()
{
    #enabled(1),
    #disabled(2),
    #empty(3),
    #cached (4),
    #expired(5)

    $SNMPSET NET-SNMP-AGENT-MIB::nsCacheStatus.1.3.6.1.2.1.198.2.2.1.3 = $1; STATUS $?
    $SNMPSET NET-SNMP-AGENT-MIB::nsCacheStatus.1.3.6.1.2.1.198.2.2.1.6 = $1; STATUS $?
    $SNMPSET NET-SNMP-AGENT-MIB::nsCacheStatus.1.3.6.1.2.1.198.2.2.1.9 = $1; STATUS $?
}

function cache_timeout ()
{
    timeout=$1

    $SNMPSET NET-SNMP-AGENT-MIB::nsCacheTimeout.1.3.6.1.2.1.198.2.2.1.3 = $timeout; STATUS $?
    $SNMPSET NET-SNMP-AGENT-MIB::nsCacheTimeout.1.3.6.1.2.1.198.2.2.1.6 = $timeout; STATUS $?
    $SNMPSET NET-SNMP-AGENT-MIB::nsCacheTimeout.1.3.6.1.2.1.198.2.2.1.9 = $timeout; STATUS $?
}

function create_mib ()
{
    local obj=$1

    echo -e "\n-- CREATE"
    $SNMPSET SNMP-TLS-TM-MIB::snmpTlstmParamsRowStatus.$obj = 5; STATUS $?
    $SNMPSET SNMP-TLS-TM-MIB::snmpTlstmParamsClientFingerprint.$obj = "2:28 D5 F9 01 16 E5 3F D7 C7 8E 24 FE 8E 01 45 A5 2F 69 78 E6"; STATUS $?
    $SNMPSET SNMP-TLS-TM-MIB::snmpTlstmParamsStorageType.$obj = 3; STATUS $?
    $SNMPSET SNMP-TLS-TM-MIB::snmpTlstmParamsRowStatus.$obj = 1; STATUS $?
}

function get_mib ()
{
    echo -e "\n-- GET1"
    snmpbulkwalk -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TLS-TM-MIB::snmpTlstmParamsTable
}

function destroy_mib ()
{
    local obj=$1

    echo -e "\n-- INACTIVATE and DESTROY"
    # Set inactive
    $SNMPSET SNMP-TLS-TM-MIB::snmpTlstmParamsRowStatus.$obj = 2; STATUS $?
    # destroy
    $SNMPSET SNMP-TLS-TM-MIB::snmpTlstmParamsRowStatus.$obj = 6; STATUS $?
}

killall snmpd
echo '/tmp/core.%e.%p' > /proc/sys/kernel/core_pattern
ulimit -c unlimited
rm -f /tmp/core.*

snmpd -DtlstmParams -C -c $DIR/snmpd.conf -Lf /tmp/snmpd.log udp:0.0.0.0:161 udp6:[::]:161 dtlsudp:0.0.0.0:10161 dtlsudp6:[::]:10161
sleep 3

create_mib "'mytrap'"
get_mib

#cache_disable 3
#cache_timeout 1
destroy_mib "'mytrap'"
#get_mib
#get_mib

create_mib "'mytrap'"
get_mib

pgrep snmpd
if [ $? = 0 ]; then
    echo snmpd still alive
else
    echo snmpd crashed!!!!!
    gdb -batch -ex "bt" snmpd /tmp/core.*
fi
