#!/bin/sh

MIB=NET-SNMP-MIB::netSnmp.2.2.1.1.2.3.98.111.98
HOST=localhost:11167
VALGRIND_LOG=/tmp/valgrind.log
SNMPD_LOG=/tmp/snmpd.log

#snmpd_dbg="-d"

ulimit -c unlimited

# valgrind exec name is memcheck-amd64-linux
killall memcheck-amd64-linux
killall snmpd
sleep 2

snmpd $snmpd_dbg -Lf $SNMPD_LOG -x /tmp/snmp-test/var/agentx/master -c $PWD/snmpd.conf $HOST
valgrind --tool=memcheck --leak-check=full --log-file=$VALGRIND_LOG subwgt/subwgt &
valgrind_pid=$!
echo WG_PID: $valgrind_pid
sleep 5

# OK
snmpset -On -v2c -c topsecret $HOST $MIB s abc $MIB s xyz

kill -STOP $valgrind_pid
cp sd.log sd1.log
sleep 3
snmpset -On -v2c -c topsecret $HOST $MIB s abc $MIB s xyz
sleep 3
kill -CONT $valgrind_pid
sleep 2

#cat sd.log
#cat $SNMPD_LOG
grep Invalid $VALGRIND_LOG >/dev/null
if [ $? = 0 ]; then
    echo "FAIL: TEST crashed, see $VALGRIND_LOG"
else
    echo "PASS: TEST OK"
fi
    


